# Generated by Django 4.1.8 on 2023-04-24 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "email",
                    models.CharField(default="info@metatrin.com", max_length=250),
                ),
                ("location", models.CharField(default="Istanbul", max_length=100)),
                (
                    "address_details",
                    models.CharField(blank=True, default=None, max_length=500),
                ),
                ("telephone_number", models.CharField(blank=True, max_length=17)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
