# Generated by Django 4.2.8 on 2024-01-09 21:25

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_contactpage_hero_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactpage",
            name="address_details",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="email",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="location",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="telephone_number",
        ),
        migrations.AddField(
            model_name="contactpage",
            name="Information",
            field=wagtail.fields.StreamField(
                [
                    ("city_country", wagtail.blocks.CharBlock()),
                    ("address", wagtail.blocks.RichTextBlock()),
                    ("email", wagtail.blocks.EmailBlock()),
                    ("telephone_number", wagtail.blocks.CharBlock()),
                ],
                default=None,
                use_json_field=True,
            ),
        ),
    ]
