# Generated by Django 4.2.8 on 2024-01-09 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_remove_contactpage_address_details_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactpage",
            old_name="Information",
            new_name="information",
        ),
    ]
