# Generated by Django 4.2.8 on 2024-01-09 21:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0004_rename_information_contactpage_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactpage",
            name="hero_title",
            field=wagtail.fields.StreamField(
                [("title", wagtail.blocks.CharBlock())],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
