# Generated by Django 4.2.8 on 2024-01-10 11:34

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0005_alter_contactpage_hero_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactpage",
            name="hero_title",
            field=wagtail.fields.StreamField(
                [("block", wagtail.blocks.CharBlock())],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
