# Generated by Django 4.2.8 on 2024-02-08 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0007_contactpage_from_address_contactpage_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactpage",
            name="from_address",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="thank_you_text",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="to_address",
        ),
        migrations.DeleteModel(
            name="FormField",
        ),
    ]
