# Generated by Django 4.2.8 on 2024-02-08 22:20

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0009_alter_contactpage_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactpage",
            name="information",
            field=wagtail.fields.StreamField(
                [
                    (
                        "office",
                        wagtail.blocks.StructBlock(
                            [
                                ("city_country", wagtail.blocks.CharBlock()),
                                ("address", wagtail.blocks.CharBlock()),
                                ("email", wagtail.blocks.EmailBlock()),
                                ("telephone_number", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    )
                ],
                default=None,
                use_json_field=True,
            ),
        ),
    ]
