# Generated by Django 4.2.8 on 2024-03-07 19:05

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blogcategory_blogtagindexpage_alter_blogpage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="post_body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
