# Generated by Django 4.2.8 on 2024-03-17 19:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_rename_hero_subtilte_blogindexpage_hero_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindexpage",
            name="hero_title",
            field=wagtail.fields.StreamField(
                [("title", wagtail.blocks.CharBlock())], blank=True, null=True
            ),
        ),
    ]
