# Generated by Django 4.2.8 on 2024-03-17 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_blogindexpage_hero_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogindexpage",
            old_name="hero_subtitle",
            new_name="blog_hero_subtitle",
        ),
        migrations.RenameField(
            model_name="blogindexpage",
            old_name="hero_title",
            new_name="blog_hero_title",
        ),
    ]
