# Generated by Django 4.2.8 on 2024-03-17 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_rename_hero_subtitle_blogindexpage_blog_hero_subtitle_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogindexpage",
            old_name="blog_hero_subtitle",
            new_name="hero_subtitle",
        ),
        migrations.RenameField(
            model_name="blogindexpage",
            old_name="blog_hero_title",
            new_name="hero_title",
        ),
    ]
