# Generated by Django 4.2.8 on 2024-03-17 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_rename_blog_hero_subtitle_blogindexpage_hero_subtitle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="main_header",
        ),
    ]
