# Generated by Django 4.2.8 on 2024-03-17 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_remove_blogpage_main_header"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpage",
            options={"ordering": ["pub_date", "title"]},
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="post_title",
        ),
    ]
