# Generated by Django 4.2.8 on 2024-03-19 12:50

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_blogcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcomment",
            name="content_object",
            field=modelcluster.fields.ParentalKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_comment",
                to="blog.blogpage",
            ),
        ),
    ]
