# Generated by Django 4.2.8 on 2024-03-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_rename_blogpage_blogcomment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="author",
            field=models.CharField(max_length=255),
        ),
    ]
