# Generated by Django 4.2.8 on 2024-03-19 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_alter_blogcomment_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcomment",
            options={"ordering": ["created_at"]},
        ),
        migrations.RenameField(
            model_name="blogcomment",
            old_name="post",
            new_name="page",
        ),
        migrations.RemoveField(
            model_name="blogcomment",
            name="active",
        ),
        migrations.RemoveField(
            model_name="blogcomment",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="blogcomment",
            name="updated_at",
        ),
    ]
