# Generated by Django 4.2.8 on 2024-03-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0092_query_searchpromotion_querydailyhits"),
        ("blog", "0014_alter_blogcomment_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogComment",
            new_name="Comment",
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
        migrations.AlterField(
            model_name="comment",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="wagtailcore.page",
            ),
        ),
    ]
