# Generated by Django 4.2.8 on 2024-03-19 16:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_rename_blogcomment_comment_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPageComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("comment", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("author", models.CharField(max_length=255)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blogpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
