# Generated by Django 4.2.8 on 2024-03-19 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_blogpagecomments_delete_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPageComments",
        ),
    ]
