# Generated by Django 4.1.8 on 2023-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(default="Design", max_length=250),
        ),
    ]
