# Generated by Django 4.2.8 on 2023-12-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_homepage_hero_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_title",
            field=models.TextField(
                default="Design, Develop, Dominante", max_length=250
            ),
        ),
    ]
