# Generated by Django 4.2.8 on 2023-12-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_homepage_hero_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_title",
            field=models.TextField(default="Design, Develop, Dominante"),
        ),
    ]
