# Generated by Django 4.2.8 on 2023-12-20 11:57

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_homepage_hero_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_title",
            field=wagtail.fields.StreamField(
                [("title", wagtail.blocks.CharBlock())],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
