# Generated by Django 4.2.8 on 2023-12-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_homepage_hero_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="slogan",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
