# Generated by Django 4.2.8 on 2024-01-05 21:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_homepage_slogan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="mission",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="vision",
        ),
        migrations.CreateModel(
            name="BusinessStatement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("body", wagtail.fields.RichTextField(max_length=1000)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_statement",
                        to="home.homepage",
                    ),
                ),
            ],
        ),
    ]
