# Generated by Django 4.2.8 on 2024-01-05 22:12

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_remove_homepage_mission_remove_homepage_vision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessstatement",
            name="body",
            field=wagtail.fields.RichTextField(),
        ),
    ]
