# Generated by Django 4.2.8 on 2024-01-05 22:14

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_businessstatement_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="call_to_action",
            field=wagtail.fields.RichTextField(),
        ),
    ]
