# Generated by Django 4.2.8 on 2024-01-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_homepage_call_to_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="call_to_action",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
