# Generated by Django 4.2.8 on 2024-01-05 23:02

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_homepage_call_to_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="call_to_action",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
