# Generated by Django 4.2.8 on 2024-01-09 11:57

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_homepage_call_to_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="call_to_action",
            field=wagtail.fields.StreamField(
                [("items", wagtail.blocks.CharBlock())],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
