# Generated by Django 4.2.8 on 2024-01-10 11:34

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_alter_homepage_call_to_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="content_row",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
