# Generated by Django 4.2.8 on 2024-01-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_homepage_content_row"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content_row",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
