# Generated by Django 4.2.8 on 2024-01-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_alter_homepage_content_row"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessstatement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
