# Generated by Django 4.1.8 on 2023-04-26 13:45

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="services",
            field=wagtail.fields.RichTextField(max_length=500),
        ),
    ]
