# Generated by Django 4.2.8 on 2023-12-17 14:23

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0002_alter_aboutpage_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="services",
            field=wagtail.fields.RichTextField(max_length=600),
        ),
    ]
