# Generated by Django 4.2.8 on 2023-12-20 12:47

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0003_alter_aboutpage_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="hero_title",
            field=wagtail.fields.StreamField(
                [("block", wagtail.blocks.CharBlock())],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
