# Generated by Django 4.2.8 on 2023-12-21 09:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0004_aboutpage_hero_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="services_item",
            field=wagtail.fields.StreamField(
                [("block", wagtail.blocks.CharBlock())],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
