# Generated by Django 4.2.8 on 2024-01-03 09:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0005_alter_aboutpage_services_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="TitleMovingOuter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    wagtail.fields.RichTextField(blank=True, max_length=300, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="big_title",
                        to="about.aboutpage",
                    ),
                ),
            ],
        ),
    ]
