# Generated by Django 4.2.8 on 2024-01-03 10:23

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0006_titlemovingouter"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="big_title",
            field=wagtail.fields.RichTextField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name="TitleMovingOuter",
        ),
    ]
