# Generated by Django 4.2.8 on 2024-01-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0007_aboutpage_big_title_delete_titlemovingouter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="big_title",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
