# Generated by Django 4.2.8 on 2024-01-03 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0008_alter_aboutpage_big_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutpage",
            old_name="big_title",
            new_name="Title Moving Outer",
        ),
    ]
