# Generated by Django 4.2.8 on 2024-01-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0009_rename_big_title_aboutpage_title_moving_outer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpage",
            name="Title Moving Outer",
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="big_title",
            field=models.TextField(
                blank=True, max_length=250, null=True, verbose_name="Title Moving Outer"
            ),
        ),
    ]
