# Generated by Django 4.2.8 on 2024-01-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0010_remove_aboutpage_title_moving_outer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpagefaq",
            name="overview_detail",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="aboutpagefaq",
            name="overview_title",
            field=models.CharField(max_length=300),
        ),
    ]
