# Generated by Django 4.2.8 on 2024-01-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0011_alter_aboutpagefaq_overview_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpagefaq",
            name="overview_detail",
            field=models.CharField(max_length=1000),
        ),
    ]
