# Generated by Django 4.2.8 on 2024-01-05 20:58

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0012_alter_aboutpagefaq_overview_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("body", models.CharField(max_length=1000)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_insight",
                        to="about.aboutpage",
                    ),
                ),
            ],
        ),
    ]
