# Generated by Django 4.2.8 on 2024-01-05 21:00

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0013_businessinsight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessinsight",
            name="body",
            field=wagtail.fields.RichTextField(max_length=1000),
        ),
    ]
