# Generated by Django 4.2.8 on 2024-01-09 19:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0014_alter_businessinsight_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapShot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("count_field", models.IntegerField(blank=True, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snap_shot",
                        to="about.aboutpage",
                    ),
                ),
            ],
        ),
    ]
