# Generated by Django 4.2.8 on 2024-01-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0015_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="content_row",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
