# Generated by Django 4.2.8 on 2024-02-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0016_aboutpage_content_row"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snapshot",
            old_name="title",
            new_name="row_title",
        ),
        migrations.AddField(
            model_name="snapshot",
            name="snapshot_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
