# Generated by Django 4.2.8 on 2024-03-18 00:47

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0017_rename_title_snapshot_row_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snapshot",
            name="count_field",
        ),
        migrations.RemoveField(
            model_name="snapshot",
            name="row_title",
        ),
        migrations.RemoveField(
            model_name="snapshot",
            name="snapshot_title",
        ),
        migrations.AddField(
            model_name="snapshot",
            name="snap_shot",
            field=wagtail.fields.StreamField(
                [
                    (
                        "snap_shot",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("amount", wagtail.blocks.IntegerBlock()),
                            ]
                        ),
                    )
                ],
                default=None,
            ),
        ),
    ]
