# Generated by Django 4.2.8 on 2024-03-18 01:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0018_remove_snapshot_count_field_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SnapShot",
        ),
    ]
