# Generated by Django 4.2.8 on 2023-12-20 12:34

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioindexpage",
            name="hero_title",
            field=wagtail.fields.StreamField(
                [("title", wagtail.blocks.CharBlock())],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
