# Generated by Django 4.2.8 on 2024-03-17 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookMarkProject",
        ),
    ]
