# Generated by Django 4.2.8 on 2023-12-23 16:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("portfolio", "0002_portfolioindexpage_hero_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliopage",
            name="banner_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_gallery",
                to="portfolio.portfoliopage",
            ),
        ),
        migrations.DeleteModel(
            name="PortfolioPageGalleryImage",
        ),
    ]
