# Generated by Django 4.2.8 on 2023-12-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_portfoliopage_banner_image_alter_gallery_page_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioIndustryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Industry categories",
            },
        ),
    ]
