# Generated by Django 4.2.8 on 2023-12-23 18:12

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_portfolioindustrycategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolioindustrycategory",
            options={"verbose_name_plural": "portfolio industry"},
        ),
        migrations.AddField(
            model_name="portfoliopage",
            name="industries",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="portfolio.portfolioindustrycategory"
            ),
        ),
    ]
