# Generated by Django 4.2.8 on 2023-12-25 13:04

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_alter_portfolioindustrycategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioTechnologyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "portfolio technology",
            },
        ),
        migrations.AddField(
            model_name="portfoliopage",
            name="technologies",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="portfolio.portfoliotechnologycategory"
            ),
        ),
    ]
