# Generated by Django 4.2.8 on 2023-12-26 23:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_portfoliotechnologycategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfoliopage",
            name="overview",
        ),
    ]
